language: scala
scala:
   - 2.9.3
   - 2.10.7
   - 2.11.12
   - 2.12.4
jdk:
  - oraclejdk8
dist: trusty
sudo: false
script:
  - sbt clean coverage test fun:test coverageReport && sbt coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
