language: scala
scala:
   - 2.12.4
   - 2.11.12
   - 2.10.7
   - 2.9.3
jdk:
  - oraclejdk8
  - openjdk8
dist: trusty
sudo: false
script:
  - sbt clean scalafmt::test test:scalafmt::test it:scalafmt::test jacoco it:jacoco coverage test it:test assembly coverageReport && sbt coverageAggregate && sbt stats scalastyle
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
